### ISSUE TITLE
Panic due to extra spaces

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/release-toolkit#121]
This works
```
## Unreleased

### Bugfix
- `imagePullPolicy` is now correctly applied to the init container as well.
```

The same with extra spaces causes a panic:
```
## Unreleased

### Bugfix
- `imagePullPolicy` is now correctly applied to the init container as well.    <--this are extra spaces
```

Trace 😱 
```
panic: node *ast.Hardbreak NYI

goroutine 1 [running]:
github.com/gomarkdown/markdown/md.(*Renderer).RenderNode(0x100f9c108?, {0x1009c4160?, 0x14000092690?}, {0x1009ca698?, 0x140003fc960?}, 0x60?)
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/md/md_renderer.go:293 +0xa30
github.com/gomarkdown/markdown.Render.func1({0x1009ca698?, 0x140003fc960?}, 0xf8?)
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/markdown.go:63 +0x50
github.com/gomarkdown/markdown/ast.NodeVisitorFunc.Visit(0x140005e4240?, {0x1009ca698?, 0x140003fc960?}, 0x58?)
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/ast/node.go:563 +0x38
github.com/gomarkdown/markdown/ast.Walk({0x1009ca698, 0x140003fc960}, {0x1009c57c0, 0x14000076340})
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/ast/node.go:535 +0x58
github.com/gomarkdown/markdown/ast.Walk({0x1009ca9b0, 0x140005e4240}, {0x1009c57c0, 0x14000076340})
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/ast/node.go:546 +0x140
github.com/gomarkdown/markdown/ast.WalkFunc(...)
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/ast/node.go:569
github.com/gomarkdown/markdown.Render({0x1009ca9b0, 0x140005e4240}, {0x1009c7ef8, 0x1400062c300})
        /Users/pgallina/go/pkg/mod/github.com/gomarkdown/markdown@v0.0.0-20220627144906-e9a81102ebeb/markdown.go:62 +0xd8
github.com/newrelic/release-toolkit/src/changelog/sources/markdown.items({0x140000761d0?, 0x1, 0x10080a576?})
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/src/changelog/sources/markdown/md.go:164 +0x28c
github.com/newrelic/release-toolkit/src/changelog/sources/markdown.builder.entriesFromHeader({0x140003fdb80?, 0x140004683c0?, 0x140000925a0?}, 0x140003fdc20, {0x1007f0c4f, 0x6})
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/src/changelog/sources/markdown/md.go:110 +0xec
github.com/newrelic/release-toolkit/src/changelog/sources/markdown.builder.build({0x140003fdb80, 0x0?, 0x0?})
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/src/changelog/sources/markdown/md.go:82 +0x384
github.com/newrelic/release-toolkit/src/changelog/sources/markdown.Markdown.Changelog({{0x1009c50a0?, 0x14000554378?}})
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/src/changelog/sources/markdown/md.go:50 +0x7c
github.com/newrelic/release-toolkit/src/app/generate.Generate(0x140001e4940)
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/src/app/generate/generate.go:151 +0x46c
github.com/urfave/cli/v2.(*Command).Run(0x100cec900, 0x140001e4640)
        /Users/pgallina/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/command.go:173 +0x5ac
github.com/urfave/cli/v2.(*App).RunContext(0x140001a2540, {0x1009c8e10?, 0x140000280d0}, {0x14000020080, 0x8, 0x8})
        /Users/pgallina/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:383 +0xb90
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/pgallina/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:252
main.main()
        /Users/pgallina/go/pkg/mod/github.com/newrelic/release-toolkit@v0.0.0-20221019154739-6d5181fc033d/main.go:11 +0x48
exit status 2
make: *** [_release-changes-chart] Error 1

```

**Comment by roobre** [comment]
This is pretty weird, I've opened a PR [here](https://github.com/newrelic/release-toolkit/pull/125) to reproduce this on a test case. I'll investigate and try to see what can be causing this.
